dct/urls.py
from django.urls import path

from .views import (
    AccumulatorCreateView, AccumulatorListView, AccumulatorUpdateView,
    AccumulatorDeleteView,
    DataCollectTerminalCreateView, DataCollectTerminalDeleteView, DataCollectTerminalListView,
    DataCollectTerminalUpdate,
    EquipmentListView, DCTRemarkListView
)


urlpatterns = [
    path('create_dct/', DataCollectTerminalCreateView.as_view(), name='create_dct_url'),
    path('list_dct', DataCollectTerminalListView.as_view(), name='list_dct_url'),
    path('update_dct/<str:slug>/', DataCollectTerminalUpdate.as_view(), name='update_dct_url'),
    path('delete_dct/<str:slug>/', DataCollectTerminalDeleteView.as_view(), name='delete_dct_url'),

    path('create_accumulator/', AccumulatorCreateView.as_view(), name='create_accumulator_url'),
    path('list_accumulator', AccumulatorListView.as_view(), name='list_accumulator_url'),
    path('update_accumulator/<int:pk>/', AccumulatorUpdateView.as_view(), name='update_accumulator_url'),
    path('delete_accumulator/<int:pk>/', AccumulatorDeleteView.as_view(), name='delete_accumulator_url'),

    path('list_equipment/', EquipmentListView.as_view(), name='list_equipment_url'),
    path('list_dctremark/<str:slug>/', DCTRemarkListView.as_view(), name='list_dctremark_url')
]

inportal/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('accounts/', include('account.urls')),
    path('dct/', include('dct.urls')),
    path('client/', include('client.urls')),
    path('blog/', include('blog.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dct/models.py
from textwrap import dedent

from django.db import models
from django.db.models import Q, F, Value
from django.db.models.functions import Concat
from django.urls import reverse
from django.utils import timezone

from client.models import Client
from .utils import is_ru


class DataCollectTerminal(models.Model):
    """Data Collect Terminal"""
    MODELS = (
        (1, 'Motorola MC7596'),
        (2, 'Motorola MC7598'),
        (3, 'Motorola MC7090'),
        (4, 'Motorola MC9090ER'),
        (5, 'Intermec CK3a1'),
        (6, 'Intermec CK3n1'),
    )
    name = models.CharField(primary_key=True, max_length=50, db_index=True,
                            verbose_name='Наименование')
    slug = models.SlugField(max_length=50, blank=True, unique=True)
    model = models.IntegerField(choices=MODELS, default=1, verbose_name='Модель')
    serial_number = models.CharField(max_length=50, unique=True,
                                     verbose_name='Серийный номер')
    mac_address = models.CharField(max_length=20, unique=True, db_index=True,
                                   verbose_name='MAC-адрес')
    user = models.OneToOneField(Client, null=True, blank=True,
                                on_delete=models.PROTECT, verbose_name='Пользователь')
    accumulator = models.OneToOneField('Accumulator', null=True, blank=True,
                                       on_delete=models.PROTECT, verbose_name='Аккумулятор')
    remark = models.TextField(null=True, blank=True, verbose_name='Примечание')
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    debited = models.BooleanField(default=False, verbose_name='Списан')
    repair = models.BooleanField(default=False, verbose_name='В ремонте')

    def __str__(self):
        return self.name

    def __gt__(self, other):
        return int(self.name[4:]) > int(other.name[4:])

    def save(self, *args, **kwargs):
        self.slug = is_ru(self.name)
        return super().save(*args, **kwargs)

    def get_absolute_url(self):
        """Method for getting the absolute path of an instance."""
        return reverse('update_dct_url', kwargs={'slug': self.slug})

    @classmethod
    def order(cls, order: str):
        """
        Sorting terminals by the passed value.

        Returns a QuerySet.
        """
        if order == '-number':
            sorted_data = sorted(cls.objects.all(), reverse=True)
        elif order == 'user':
            sorted_data = cls.objects.order_by('user')
        elif order == '-user':
            sorted_data = cls.objects.raw(
                dedent('''\
                    SELECT *
                    FROM dct_datacollectterminal
                    LEFT JOIN client_client ON user_id=client_client.id
                    ORDER BY client_client.client DESC NULLS LAST;'''))
        elif order == 'accum':
            # sorted_data = cls.objects.order_by('accumulator')
            word = 'tsd-2 8354520800990'
            # sorted_data = cls.objects.raw("SELECT * FROM dct_datacollectterminal WHERE CONCAT(slug, ' ', serial_number) LIKE %s", [word])
            sorted_data = cls.objects.annotate(full_name=Concat(F('slug'), Value(' '), F('serial_number'))).filter(
                full_name__icontains=word)
        elif order == '-accum':
            sorted_data = cls.objects.raw(
                dedent('''\
                    SELECT *
                    FROM dct_datacollectterminal
                    ORDER BY accumulator_id DESC NULLS LAST;'''))
        else:
            sorted_data = sorted(cls.objects.all())
        return sorted_data

    @classmethod
    def get_special_queryset(cls, dct=None, user=None):
        """
        Excluded from the drop-down list of decommissioned batteries,
        batteries linked to other terminals.
        The battery connected to this terminal is included in the list
        if the terminal already exists.
        Excludes from the list of users to which the terminal is already linked.

        Returns a dictionary QuerySet.
        """
        qs = {}
        q_accum = Q(debited=False) & (Q(datacollectterminal__isnull=True) | Q(datacollectterminal=dct))
        qs['qs_accum'] = Accumulator.objects.filter(q_accum)
        q_user = Q(datacollectterminal__isnull=True) | Q(client=user)
        qs['qs_user'] = Client.objects.filter(q_user)
        return qs

    class Meta:
        verbose_name_plural = 'ТСД'
        verbose_name = 'ТСД'


class DataCollectTerminalRemark(models.Model):
    """Remark for data collect terminal."""
    data_collect_terminal = models.ForeignKey(DataCollectTerminal, null=True,
                                              blank=True, on_delete=models.CASCADE)
    remark = models.TextField(null=True, blank=True, verbose_name='Примечание')
    date = models.DateTimeField(verbose_name='Дата')

    def __str__(self):
        return f'{self.data_collect_terminal}: {self.remark} - ' \
               f'{self.date.strftime("%Y.%m.%d %I:%M")}'

    class Meta:
        verbose_name = 'Примечание'
        verbose_name_plural = 'Примечания'
        ordering = ['-date']


class Accumulator(models.Model):
    """Accumulator for Date Collect Terminal"""
    number = models.IntegerField(primary_key=True, db_index=True, verbose_name='Номер')
    remark = models.TextField(null=True, blank=True, verbose_name='Примечание')
    date_purchase = models.DateTimeField(auto_now_add=True, verbose_name='Дата закупки')
    debited = models.BooleanField(default=False, verbose_name='Списан')

    def __str__(self):
        return str(self.number)

    class Meta:
        verbose_name_plural = 'Аккумуляторы'
        verbose_name = 'Аккумулятор'
        ordering = ['number']

    def get_absolute_url(self):
        """Method for getting the absolute path of an instance."""
        return reverse('update_accumulator_url', kwargs={'pk': self.pk})

    def changed_status(self, state):
        """
        Changing the battery status.
        Possible states:
        1. Installed
        2. Uninstalled
        """
        AccumulatorDate.objects.create(state=state, accumulator=self)

    def lifetime(self) -> int:
        """Returns the number of days worked by the battery."""
        sum_ = 0
        if self.accumulatordate_set.all():
            for accumulator_date in self.accumulatordate_set.all():
                if accumulator_date.state == 1:
                    start = accumulator_date.date
                else:
                    stop = accumulator_date.date
                    delta = stop - start
                    sum_ += delta.days
            if accumulator_date.state == 1:
                delta = timezone.now() - start
                sum_ += delta.days
            return sum_
        return 0

    @classmethod
    def get_special_queryset(cls, order=None, filtering=None):
        """Get a special queryset."""
        qs = Accumulator.objects.all()
        if filtering:
            filters = filtering.split()
            for filter_ in filters:
                if filter_ == 'debited':
                    qs = qs.filter(debited=True)
                if filter_ == '-debited':
                    qs = qs.filter(debited=False)
        if order == '-number':
            qs = qs.order_by('-number')
        return qs


class AccumulatorDate(models.Model):
    """
    This class contains data about the date of installation and the date of
    removal of the batteries from the data collection terminals.
    """
    STATE = (
        (1, 'Install'),
        (2, 'Uninstall'),
    )
    date = models.DateTimeField(auto_now_add=True, verbose_name='Дата')
    state = models.IntegerField(choices=STATE, default=1,
                                verbose_name='Состояние')
    accumulator = models.ForeignKey(Accumulator, on_delete=models.CASCADE,
                                    verbose_name='Дата изменения состояния')

    def __str__(self):
        return f'{self.accumulator}: {self.state} - {self.date.strftime("%Y.%m.%d %I:%M")}'

    class Meta:
        ordering = ['date']

dct/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView

from .forms import DCTForm
from .mixins import ModifiedMethodFormValidMixim, SuccessURLAccumMixin
from .models import DataCollectTerminal, Accumulator
from .utils import add_order_filter_context


class DataCollectTerminalCreateView(LoginRequiredMixin, ModifiedMethodFormValidMixim, CreateView):
    """Create data collection terminal."""
    model = DataCollectTerminal
    template_name = 'dct/datacollectterminal_create.html'
    form_class = DCTForm
    success_url = reverse_lazy('list_dct_url')

    def get_form(self, form_class=DCTForm, **kwargs):
        """
        Excluded from the drop-down list of decommissioned batteries,
        batteries linked to other terminals.
        Excludes from the list of users to which the terminal is already linked.
        """
        form = super().get_form(**kwargs)
        qs = DataCollectTerminal.get_special_queryset()
        form.fields['accumulator'].queryset = qs.get('qs_accum')
        form.fields['user'].queryset = qs.get('qs_user')
        return form


class DataCollectTerminalListView(LoginRequiredMixin, ListView):
    """Output a list of data collection terminals."""
    model = DataCollectTerminal

    def get_context_data(self, **kwargs):
        """
        Adds sorted data by user, battery number, or truncated name field
        number to the context.
        Adds the value by which the sorting was performed to the context.
        """
        context = super().get_context_data(**kwargs)
        order = self.request.GET.get('order', '')
        context['order'] = order
        context['datacollectterminal_list'] = DataCollectTerminal.order(order)
        return context


class DataCollectTerminalUpdate(LoginRequiredMixin, ModifiedMethodFormValidMixim, UpdateView):
    """Update the selected data collection terminal."""
    model = DataCollectTerminal
    template_name = 'dct/datacollectterminal_update.html'
    form_class = DCTForm

    def get_context_data(self, **kwargs):
        """Adding a sortation order to the context."""
        context = super().get_context_data(**kwargs)
        context['order'] = self.request.GET.get('order', '')
        return context

    def get_success_url(self):
        """
        Redirects to a page with the sorting that was set when you went
        to this page.
        """
        order = self.request.GET.get('order', '')
        return f"{reverse_lazy('list_dct_url')}?order={order}"

    def get_form(self, form_class=DCTForm, **kwargs):
        """
        Excluded from the drop-down list of decommissioned batteries,
        batteries linked to other terminals.
        Excludes from the list of users to which the terminal is already linked.
        """
        form = super().get_form(**kwargs)
        qs = DataCollectTerminal.get_special_queryset(self.object, self.object.user)
        form.fields['accumulator'].queryset = qs.get('qs_accum')
        form.fields['user'].queryset = qs.get('qs_user')
        return form


class DataCollectTerminalDeleteView(LoginRequiredMixin, DeleteView):
    """Delete data collection terminal."""
    model = DataCollectTerminal
    template_name = 'dct/datacollectterminal_delete.html'

    def delete(self, request, *args, **kwargs):
        """
        Changing the status of the battery to extracted when deleting
        the terminal.
        """
        dct = self.get_object()
        if dct.accumulator:
            dct.accumulator.changed_status(2)
        return super().delete(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        """Adding a sorting order to the context."""
        context = super().get_context_data(**kwargs)
        context['order'] = self.request.GET.get('order', '')
        return context

    def get_success_url(self):
        """
        Redirects to a page with the sorting that was set when you
        went to this page.
        """
        order = self.request.GET.get('order', '')
        return f"{reverse_lazy('list_dct_url')}?order={order}"


class AccumulatorCreateView(LoginRequiredMixin, SuccessURLAccumMixin, CreateView):
    """Create accumulator."""
    model = Accumulator
    template_name = 'dct/accumulator_create.html'
    fields = ['number', 'debited', 'remark']

    def get_context_data(self, **kwargs):
        """Adding sorting and filtering data to the context."""
        context = super().get_context_data(**kwargs)
        context.update(add_order_filter_context(self.request))
        return context


class AccumulatorListView(LoginRequiredMixin, ListView):
    """Output a list of accumulators."""
    model = Accumulator

    def get_context_data(self, **kwargs):
        """Adding sorting and filtering data to the context."""
        context = super().get_context_data(**kwargs)
        filtering = self.request.GET.get('filtering', '')
        context['filtering'] = filtering
        order = self.request.GET.get('order', '')
        context['order'] = order
        qs = Accumulator.get_special_queryset(order=order, filtering=filtering)
        context['accumulator_list'] = qs
        return context


class AccumulatorUpdateView(LoginRequiredMixin, SuccessURLAccumMixin, UpdateView):
    """Update the selected accumulator."""
    model = Accumulator
    template_name = 'dct/accumulator_update.html'
    fields = ['number', 'debited', 'remark']

    def get_context_data(self, **kwargs):
        """Adding sorting and filtering data to the context."""
        context = super().get_context_data(**kwargs)
        context.update(add_order_filter_context(self.request))
        return context


class AccumulatorDeleteView(LoginRequiredMixin, SuccessURLAccumMixin, DeleteView):
    """Delete accumulator."""
    model = Accumulator
    template_name = 'dct/accumulator_delete.html'

    def get_context_data(self, **kwargs):
        """Adding sorting and filtering data to the context."""
        context = super().get_context_data(**kwargs)
        context.update(add_order_filter_context(self.request))
        return context


class EquipmentListView(LoginRequiredMixin, TemplateView):
    """Equipment List"""
    template_name = 'dct/equipment_list.html'


class DCTRemarkListView(LoginRequiredMixin, TemplateView):
    """List of terminal notes."""
    template_name = 'dct/dctremark_list.html'

    def get_context_data(self, **kwargs):
        """Adding a list of notes for a specific terminal to the context."""
        context = super().get_context_data(**kwargs)
        dct = get_object_or_404(DataCollectTerminal, slug=context['slug'])
        context['dctremarks'] = dct.datacollectterminalremark_set.all()
        return context

dct/templates/dct/accumulator_create.html
{% extends "basic.html" %}

{% block title %}
    Добавление аккумулятора
{% endblock %}

{% block content %}
    <h3>Добавление записи</h3>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input class="bottom-10px" type="submit" value="Добавить">
    </form>
{% endblock %}

dct/templates/dct/accumulator_delete.html
{% extends "basic.html" %}

{% block title %}
    Удаление аккумуоятора
{% endblock %}

{% block content %}
    <h3>Удаление записи</h3>
    <form method="post">
        {% csrf_token %}
        <h5>Вы действительно хотите удалить аккумулятор №{{ accumulator.number }}?</h5>
        <a href="{{ accumulator.get_absolute_url }}?order={{ order }}&filtering={{ filtering }}"
           class="btn btn-secondary bottom-10px">Отмена</a>
        <button type="submit" name="buttom" class="btn btn-danger bottom-10px">Удалить</button>
    </form>
{% endblock %}

dct/templates/dct/accumulator_list.html
{% extends "basic.html" %}

{% block title %}
    Список аккумуляторов
{% endblock %}

{% block content %}
    <h6><a href="{% url 'create_accumulator_url' %}?order={{ order }}&filtering={{ filtering }}"
           class="btn btn-outline-primary btn-sm">
        Добавить аккумулятор</a></h6>
    Фильтровать по:
        {% if filtering == 'debited' %}
            <a href="?order={{ order }}" style="color: black"
               class="without_underscores">Списанные</a>
        {% else %}
            <a href="?order={{ order }}&filtering=debited" style="color: gray"
               class="without_underscores">Списанные</a>
        {% endif %}

        {% if filtering == '-debited' %}
            <a href="?order={{ order }}" style="color: black"
               class="without_underscores">Не списанные</a>
        {% else %}
            <a href="?order={{ order }}&filtering=-debited" style="color: gray"
               class="without_underscores">Не списанные</a>
        {% endif %}

    <table class="table table-striped">
        <thead class="thead-light">
            <tr>

                {% if order == 'number' %}
                <th>
                    <a href="?order=-number&filtering={{ filtering }}" class="without_underscores" style="color: black">
                        Номер<img class="arrow" src="/static/down_arrow.png" alt="v">
                    </a>
                </th>
                {% elif order == '-number' %}
                <th>
                    <a href="?order=number&filtering={{ filtering }}" class="without_underscores" style="color: black">
                        Номер<img class="arrow" src="/static/up_arrow.png" alt="^">
                    </a>
                </th>
                {% elif not order %}
                <th>
                    <a href="?order=-number&filtering={{ filtering }}" class="without_underscores" style="color: black">
                        Номер<img class="arrow" src="/static/down_arrow.png" alt="v">
                    </a>
                </th>
                {% else %}
                <th>
                    <a href="?order=number&filtering={{ filtering }}" class="without_underscores" style="color: black">
                        Номер<img class="arrow" src="/static/down_arrow_grey.png" alt="v" style="color: grey">
                    </a>
                </th>
                {% endif %}

                <th>Примечание</th>
            </tr>
        </thead>
        <tbody>
            {% for accumulator in accumulator_list %}
                <tr>
                    <td>
                        <h6>
                            <a href="{% url 'update_accumulator_url' pk=accumulator.pk %}?order={{ order }}&filtering={{ filtering }}">
                                {{ accumulator.number }}
                            </a>
                        </h6>
                    </td>
                    <td>
                        <p>
                            {{ accumulator.remark }}
                        </p>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

dct/templates/dct/accumulator_update.html
{% extends "basic.html" %}

{% block title %}
    Обновление аккумулятора
{% endblock %}

{% block content %}
    <h3>Изменение записи</h3>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <p><h6><b>Колличество отработанных дней: {{ accumulator.lifetime }}</b></h6></p>
        <a href="{% url 'list_accumulator_url' %}?order={{ order }}&filtering={{ filtering }}"
           class="btn btn-secondary bottom-10px">Назад</a>
        <input type="submit" value="Сохранить" class="btn btn-secondary bottom-10px">
        <a href="{% url 'delete_accumulator_url' pk=object.pk %}?order={{ order }}&filtering={{ filtering }}"
           class="btn btn-danger bottom-10px">Удалить</a>
    </form>
{% endblock %}

dct/templates/dct/datacollectterminal_create.html
{% extends "basic.html" %}

{% block title %}
    Добавление ТСД
{% endblock %}

{% block content %}
    <h3>Добавление записи</h3>
    <form method="post">
        {% csrf_token %}
        <table>
            {% for field in form %}
                <tr>
                    <th>
                        {{ field.label }}
                    </th>
                    <td>
                        {% if field.errors %}
                            <div class="alert-danger" role="alert">{{ field.errors }}</div>
                        {% endif %}
                        {{ field }}
                        <br><span class="helptext text-secondary">{{ field.help_text }}</span>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <input class="bottom-10px" type="submit" value="Добавить">
    </form>
{% endblock %}

dct/templates/dct/datacollectterminal_delete.html
{% extends "basic.html" %}

{% block title %}
    Удаление ТСД
{% endblock %}

{% block content %}
    <h3>Удаление записи</h3>
    <form method="post">
        {% csrf_token %}

        <h5>Вы действительно хотите удалить <b>'{{ datacollectterminal.name|upper }}'</b>?</h5>
        <a href="{{ datacollectterminal.get_absolute_url }}?order={{ order }}" class="btn btn-secondary bottom-10px">Отмена</a>
        <button type="submit" name="buttom" class="btn btn-danger bottom-10px">Удалить</button>

    </form>
{% endblock %}

dct/templates/dct/datacollectterminal_list.html
{% extends "basic.html" %}

{% block title %}
    Список ТСД
{% endblock %}

{% block content %}

    <a href="{% url 'create_dct_url' %}" class="btn btn-outline-primary btn-sm">Добавить ТСД</a>

    <table class="table table-striped">
        <thead class="thead-light">
        <tr>

            {% if order == 'number' %}
                <th>
                    <a href="?order=-number" class="without_underscores" style="color: black">Номер
                        <img class="arrow" src="/static/down_arrow.png" alt="v">
                    </a>
                </th>
            {% elif order == '-number' %}
                <th>
                    <a href="?order=number" class="without_underscores" style="color: black">Номер
                        <img class="arrow" src="/static/up_arrow.png" alt="^">
                    </a>
                </th>
            {% elif not order %}
                <th>
                    <a href="?order=-number" class="without_underscores" style="color: black">Номер
                        <img class="arrow" src="/static/down_arrow.png" alt="v">
                    </a>
                </th>
            {% else %}
                <th>
                    <a href="?order=number" class="without_underscores" style="color: black">Номер
                        <img class="arrow" src="/static/down_arrow_grey.png" alt="v" style="color: grey">
                    </a>
                </th>
            {% endif %}

            <th>Модель</th>
            <th>Серийный номер</th>

            {% if order == 'user' %}
                <th>
                    <a href="?order=-user" class="without_underscores" style="color: black">Пользователь
                        <img class="arrow" src="/static/down_arrow.png" alt="v">
                    </a>
                </th>
            {% elif order == '-user' %}
                <th>
                    <a href="?order=user" class="without_underscores" style="color: black">Пользователь
                        <img class="arrow" src="/static/up_arrow.png" alt="^">
                    </a>
                </th>
            {% else %}
                <th>
                    <a href="?order=user" class="without_underscores" style="color: black">Пользователь
                        <img class="arrow" src="/static/down_arrow_grey.png" alt="v" style="color: grey">
                    </a>
                </th>
            {% endif %}

            <th>MAC-адрес</th>

            {% if order == 'accum' %}
                <th>
                    <a href="?order=-accum" class="without_underscores" style="color: black">S/N аккумулятора
                        <img class="arrow" src="/static/down_arrow.png" alt="v">
                    </a>
                </th>
            {% elif order == '-accum' %}
                <th>
                    <a href="?order=accum" class="without_underscores" style="color: black">S/N аккумулятора
                        <img class="arrow" src="/static/up_arrow.png" alt="^">
                    </a>
                </th>
            {% else %}
                <th>
                    <a href="?order=accum" class="without_underscores" style="color: black">S/N аккумулятора
                        <img class="arrow" src="/static/down_arrow_grey.png" alt="v" style="color: grey">
                    </a>
                </th>
            {% endif %}

            <th>Примечание</th>
        </tr>
        </thead>
        <tbody>
        {% for dct in datacollectterminal_list %}
            <tr>
                <td><h6><a href="{% url 'update_dct_url' slug=dct.slug %}?order={{ order }}">{{ dct.name }}</a></h6></td>
                <td>{{ dct.get_model_display }}</td>
                <td>{{ dct.serial_number }}</td>
                <td>
                    {% if dct.user %}
                        <p>{{ dct.user }}</p>
                    {% endif %}
                </td>
                <td>{{ dct.mac_address }}</td>
                <td>
                    {% if dct.accumulator %}
                        <p>{{ dct.accumulator }}</p>
                    {% endif %}
                </td>
                <td><p>{{ dct.remark|truncatechars:30 }}</p></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

dct/templates/dct/datacollectterminal_update.html
{% extends "basic.html" %}

{% block title %}
    Обновление ТСД
{% endblock %}

{% block content %}
    <h3>Изменение записи</h3>
    <form method="post">
        {% csrf_token %}
        <table>
            {% for field in form %}
            <tr>
                <th>
                    {{ field.label }}
                </th>
                <td>
                    {% if field.errors %}
                    <div class="alert-danger" role="alert">{{ field.errors }}</div>
                    {% endif %}
                    {% if field.name == 'name' %}
                        <input type="text" value="{{ field.value }}" disabled>
                        <input type="hidden" name="name" value="{{ field.value }}" required id="id_name">
                    {% else %}
                        {{ field }}
                    {% endif %}
                    <br><span class="helptext text-secondary">{{ field.help_text }}</span>
                </td>
            </tr>
            {% endfor %}
        </table>
        {% if datacollectterminal.accumulator %}
            <p><h6><b>Колличество отработанных дней АКБ: {{ datacollectterminal.accumulator.lifetime }}</b></h6></p>
        {% endif %}
        <p><a href="{% url 'list_dctremark_url' slug=object.slug %}" class="btn btn-outline-primary btn-sm">
            Показать историю примечаний</a></p>
        <a href="{% url 'list_dct_url' %}?order={{ order }}" class="btn btn-secondary bottom-10px">Назад</a>
        <input type="submit" value="Сохранить" class="btn btn-secondary bottom-10px">
        <a href="{% url 'delete_dct_url' slug=object.slug %}?order={{ order }}" class="btn btn-danger bottom-10px">Удалить</a>
    </form>
{% endblock %}

dct/templates/dct/dctremark_list.html
{% extends "basic.html" %}

{% block title %}
    История примечаний
{% endblock %}

{% block content %}
    <p><h5>История примечаний:</h5></p>
    {% for dctremark in dctremarks %}
        <ul>
            <li>{{ dctremark.date|date:"d.m.Y G:i" }}: <b>{{ dctremark.remark }}</b></li>
        </ul>
    {% endfor %}
{% endblock %}

dct/templates/dct/equipment_list.html
{% extends "basic.html" %}

{% block title %}
    Список оборудования
{% endblock %}

{% block content %}
    <h5>Список оборудования:</h5>
    <ul>
        <li>
            <h6><a href="{% url 'list_accumulator_url' %}">Аккумуляторы</a></h6>
        </li>
        <li>
            <h6><a href="{% url 'list_dct_url' %}">ТСД</a></h6>
        </li>
    </ul>
{% endblock %}

dct/templates/dct/index.html
{% extends "basic.html" %}
{% load static %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col-sm">
                <h5>Номер</h5>
            </div>
            <div class="col-sm">
                <h5>Модель</h5>
            </div>
            <div class="col-sm">
                <h5>Серийный номер</h5>
            </div>
            <div class="col-sm">
                <h5>Пользователь</h5>
            </div>
            <div class="col-sm">
                <h5>MAC-адрес</h5>
            </div>
            <div class="col-sm">
                <h5>S/N аккумулятора</h5>
            </div>
        </div>
    </div>

    {% for dct in dcts %}
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <h6><a href="{% url 'detail_dct' pk=dct.pk %}">{{ dct.name }}</a></h6>
                </div>
                <div class="col-sm">
                    <p>{{ dct.get_model_display }}</p>
                </div>
                <div class="col-sm">
                    <p>{{ dct.serial_number }}</p>
                </div>
                <div class="col-sm">
                    <p>{{ dct.user }}</p>
                </div>
                <div class="col-sm">
                    <p>{{ dct.mac_address }}</p>
                </div>
                <div class="col-sm">
                    <p>{{ dct.accumulator }}</p>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}